# Docker compose for local development
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - BASE_URL=http://localhost:8000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    
  # Optional: Add Redis for caching (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data:
